/**
 * Utility functions for managing wishlist markdown files
 */
import fs from 'node:fs/promises';
import path from 'node:path';

export interface WishlistMetadata {
  slug: string;
  id: number;
  projectName: string;
  repositoryUrl: string;
  maintainerUsername: string;
  maintainerAvatarUrl?: string;
  issueUrl: string;
  approved: boolean;
  wishes: string[];
  technologies: string[];
  resources: string[];
  urgency?: string;
  projectSize?: string;
  additionalNotes?: string;
  openToSponsorship?: boolean;
  preferredPractitioner?: string;
  organizationType?: string;
  organizationName?: string;
  otherOrganizationType?: string;
  nomineeName?: string;
  nomineeEmail?: string;
  nomineeGithub?: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Generate markdown content with frontmatter
 * Note: 'slug' is auto-generated by Astro from filename, so we don't include it in frontmatter
 */
function generateMarkdown(data: WishlistMetadata): string {
  return `---
id: ${data.id}
projectName: "${data.projectName}"
repositoryUrl: "${data.repositoryUrl}"
maintainerUsername: "${data.maintainerUsername}"
${data.maintainerAvatarUrl ? `maintainerAvatarUrl: "${data.maintainerAvatarUrl}"` : ''}
issueUrl: "${data.issueUrl}"
approved: ${data.approved}
wishes: ${JSON.stringify(data.wishes)}
technologies: ${JSON.stringify(data.technologies)}
resources: ${JSON.stringify(data.resources)}
${data.urgency ? `urgency: "${data.urgency}"` : ''}
${data.projectSize ? `projectSize: "${data.projectSize}"` : ''}
${data.additionalNotes ? `additionalNotes: "${data.additionalNotes.replace(/"/g, '\\"')}"` : ''}
${data.openToSponsorship !== undefined ? `openToSponsorship: ${data.openToSponsorship}` : ''}
${data.preferredPractitioner ? `preferredPractitioner: "${data.preferredPractitioner}"` : ''}
${data.organizationType ? `organizationType: "${data.organizationType}"` : ''}
${data.organizationName ? `organizationName: "${data.organizationName}"` : ''}
${data.otherOrganizationType ? `otherOrganizationType: "${data.otherOrganizationType}"` : ''}
${data.nomineeName ? `nomineeName: "${data.nomineeName}"` : ''}
${data.nomineeEmail ? `nomineeEmail: "${data.nomineeEmail}"` : ''}
${data.nomineeGithub ? `nomineeGithub: "${data.nomineeGithub}"` : ''}
createdAt: "${data.createdAt}"
updatedAt: "${data.updatedAt}"
---

# ${data.projectName}

**Maintainer**: [@${data.maintainerUsername}](https://github.com/${data.maintainerUsername})
**Repository**: [${data.repositoryUrl}](${data.repositoryUrl})

## Services Needed

${data.wishes.length > 0 ? data.wishes.map(w => `- ${w}`).join('\n') : '_No services specified_'}

${data.resources.length > 0 ? `\n## Resources Needed\n\n${data.resources.map(r => `- ${r}`).join('\n')}` : ''}

${data.technologies.length > 0 ? `\n## Technologies\n\n${data.technologies.map(t => `- ${t}`).join('\n')}` : ''}

${data.additionalNotes ? `\n## Additional Notes\n\n${data.additionalNotes}` : ''}

---

[View on GitHub](${data.issueUrl})
`;
}

/**
 * Write or update a wishlist markdown file
 * Uses slug for filename instead of issue ID
 */
export async function writeWishlistMarkdown(data: WishlistMetadata): Promise<void> {
  const contentDir = path.join(process.cwd(), 'src', 'content', 'wishlists');
  const filePath = path.join(contentDir, `${data.slug}.md`);
  
  const markdown = generateMarkdown(data);
  
  try {
    await fs.mkdir(contentDir, { recursive: true });
    await fs.writeFile(filePath, markdown, 'utf-8');
    console.log(`[wishlist-markdown] ✓ Wrote ${filePath}`);
  } catch (error) {
    console.error(`[wishlist-markdown] ✗ Failed to write ${filePath}:`, error);
    throw error;
  }
}

/**
 * Delete a wishlist markdown file by slug
 */
export async function deleteWishlistMarkdown(slug: string): Promise<void> {
  const contentDir = path.join(process.cwd(), 'src', 'content', 'wishlists');
  const filePath = path.join(contentDir, `${slug}.md`);
  
  try {
    await fs.unlink(filePath);
    console.log(`[wishlist-markdown] ✓ Deleted ${filePath}`);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      console.error(`[wishlist-markdown] ✗ Failed to delete ${filePath}:`, error);
      throw error;
    }
    // File doesn't exist, that's okay
  }
}

/**
 * Check if a wishlist markdown file exists by slug
 */
export async function wishlistMarkdownExists(slug: string): Promise<boolean> {
  const contentDir = path.join(process.cwd(), 'src', 'content', 'wishlists');
  const filePath = path.join(contentDir, `${slug}.md`);
  
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}
